// Japanese Miner v6.0 â€” The Polish Update
(()=>{
'use strict';
const VERSION='6.4.9-quests-missions-guide', SNAPSHOT_PREFIX='jm_v6_snapshots_';
const TOUR=[
 {section:'Getting started',icon:'â›ï¸',title:'Welcome to Japanese Miner',text:'Answer Japanese questions, build mastery, collect scientific gemstones, and progress from Hiragana through JLPT N1.',tips:['Create or sign in to a local player profile so every feature uses the same save.','Tap New Question or the mine rock to begin the selected course route.','Use the round menu button at the bottom-right whenever you need another game area.']},
 {section:'Getting started',icon:'ðŸ§­',title:'One-time placement test',text:'A new save may take one randomized placement assessment. Its result can recommend and unlock the correct starting mine.',tips:['The placement assessment may be completed only once per save.','Question order and answer order are randomized for that one attempt.','Earlier mines remain available for review after accepting the recommended starting point.']},
 {section:'Navigation',icon:'â˜°',title:'Explore, Gear, and Player menus',text:'The Game Menu separates progression, owned equipment, and account tools into three clear categories.',tips:['Explore contains the Expedition Hub, Course, Learning Path, Mine, Quests, and Missions.','Gear contains Shop, Inventory, Character, and the Notebook.','Player contains statistics, achievements, calendar, settings, guide, feedback, and account tools. Use â† Menu to return from any full-screen menu.']},
 {section:'Course progression',icon:'ðŸ—ºï¸',title:'Use the Expedition Hub',text:'The Expedition Hub is the world map for choosing a mine route, checking checkpoints, and entering guardian encounters.',tips:['Green or highlighted nodes are available; lock icons show what still needs progression.','Select a node to make that family, section, or level the active mining route.','The Learning Path and Course screens show the same saved mastery from different views.']},
 {section:'Course progression',icon:'ã‚',title:'Hiragana and Katakana families',text:'The two alphabet mines contain only their own kana and advance one character family at a time.',tips:['Start with Vowels, then unlock K, S, T, N, H, M, Y, R, W/N, voiced families, and P.','Reach 20% mastery in the current family to unlock the next family.','Choose families from their nodes in the Expedition Hub; the large family panel stays off the home mining screen.']},
 {section:'Course progression',icon:'èªž',title:'JLPT sections and Vocabulary levels',text:'Each JLPT mine is divided into Vocabulary, Kanji, Grammar, and Reading stops before its guardian.',tips:['Choose the section you want from its Expedition Hub stop.','Vocabulary is split into stable 10-question sublevels; reach 20% mastery to open the next level.','The guardian still tests the full course rather than only the selected section or Vocabulary level.']},
 {section:'Questions',icon:'ðŸ“–',title:'Question help and kanji support',text:'Read the prompt, choose an answer, and use the explanation to understand why it was correct or incorrect.',tips:['The â€œI donâ€™t know this kanjiâ€ button appears only when the visible question or instruction actually contains kanji.','It stays hidden on English-, Hiragana-, and Katakana-only prompts.','Question audio and answer explanations can be adjusted in Accessibility settings.']},
 {section:'Guardian tests',icon:'ðŸ‘¹',title:'Pass the silent Boss Gate',text:'Every guardian blocks the next mine until its Perfect Gate Challenge is passed.',tips:['Each attempt draws 25 different randomized questions from the guardianâ€™s full course.','The test is silent and lasts up to 60 seconds; wrong answers are recorded instead of ending the test immediately.','Results appear after question 25 or when time expires. Only 25/25 unlocks the next mine.']},
 {section:'Goals and rewards',icon:'ðŸ“œ',title:'Complete personal Quests',text:'Quests reward consistent practice through a separate set of daily and weekly goals.',tips:['Open Quests directly from Explore.','Daily goals reset each calendar day; weekly goals reset every Monday.','Rewards include Nuggets plus Hints or Shields. Progress and claimed rewards remain in the current player save.']},
 {section:'Goals and rewards',icon:'ðŸŽ¯',title:'Run Expedition Missions',text:'Missions are daily mine-focused objectives for answering, accuracy, scheduled review, and treasure-chest progress.',tips:['Open Missions directly from Explore or from the Expedition Hub.','The dayâ€™s Nugget values are locked to the active mine when the mission board resets.','Each Sakura Garden level adds 10% to mission Nuggets; supply rewards are listed separately and are not multiplied.']},
 {section:'Mining economy',icon:'ðŸ’Ž',title:'Scientific gems and checkpoints',text:'Scientific gemstones drop from fixed mine checkpoints instead of random correct answers.',tips:['Each gemstone has a specific checkpoint, rarity, illustration, and Nugget value.','A checkpoint specimen can be claimed once, and collected gems remain visible in the Scientific Gem Collection.','Purchases spend gemstone value automatically and return change when needed.']},
 {section:'Mining economy',icon:'ðŸŽ',title:'Treasure chests and Nuggets',text:'A treasure chest appears every 25 correct answers and awards a mine-scaled Nugget amount.',tips:['Deeper mines produce larger chest rewards suited to their higher shop prices.','The Gem Forge modestly improves chest rewards.','Quests, Missions, bosses, achievements, events, and scientific drops provide additional controlled income.']},
 {section:'Shop and collection',icon:'ðŸ›ï¸',title:'Buy permanent equipment',text:'Shop purchases are permanent for the active profile and remain compatible with account backups.',tips:['Pickaxes, wallpapers, fashion, character styles, companions, supplies, and settlement upgrades have visible prices.','Locked permanent items use preview and confirmation before charging Nuggets.','Already-owned items can be equipped again without paying a second time.']},
 {section:'Companions',icon:'ðŸ¾',title:'Choose one balanced companion',text:'Only the equipped companion is active. Later companions cost more, require deeper mines, and provide modest specialized bonuses.',tips:['Companions can help with XP, review selection, supplies, chest rewards, boss rewards, or discounts.','Lion, Tiger, Panda, Squirrel, Mole, and Golem are part of the expanded roster.','Open Companions from the Expedition Hub or the organized Shop to compare exact abilities.']},
 {section:'Settlement',icon:'ðŸ˜ï¸',title:'Build long-term upgrades',text:'Settlement buildings are escalating investments designed for long-term progress rather than immediate completion.',tips:['The Sakura Garden raises daily Mission Nuggets by 10% per level.','The Gem Forge improves question-streak treasure chests.','Every purchased level is permanent and saved; later levels cost substantially more.']},
 {section:'Study tools',icon:'ðŸ§ ',title:'Smart Review and Word Book',text:'Smart Review uses spaced repetition so missed or difficult material returns sooner and mastered material waits longer.',tips:['Complete due reviews from the Expedition Hub Review tab.','Correct Japanese items enter the Word Book automatically.','The Word Book includes listening and supported browsers may offer pronunciation practice.']},
 {section:'Study tools',icon:'ðŸ““',title:'Notebook and Sticky Notes',text:'Incorrect answers enter the Notebook as difficult items without deleting the original question history.',tips:['Open Notebook from Gear or the Player Center.','Attach an 800-character Sticky Note directly to a difficult word, phrase, or question.','Create independent notes, edit or remove them, and mark difficult items reviewed without deleting their attached study context.']},
 {section:'Practice support',icon:'â¤ï¸',title:'Hearts, Shields, and silent tests',text:'Normal wrong answers can cost hearts. Shields protect one mistake, and hearts recover automatically over time.',tips:['The health timer shows when all three hearts return.','Hints can remove an incorrect choice during normal practice.','Boss testing is always silent and does not consume hearts or shields.']},
 {section:'Progress records',icon:'ðŸ“…',title:'Study time, Calendar, and Statistics',text:'Visible practice time, study dates, accuracy, streaks, and course distribution are stored with the active profile.',tips:['The Practice Calendar shows studied days, monthly activity, and total study time.','Timing pauses when the page is hidden and resumes when active again.','Statistics identify the least-practiced category and show mastery throughout the learning path.']},
 {section:'Private curriculum',icon:'ðŸ”',title:'Tutor and Admin material',text:'Tutor-provided curriculum is protected like Admin tools and remains visible only to the PIN-authenticated owner account.',tips:['Standard players cannot select, receive, review, or import protected Tutor questions.','Signing in to the authorized owner profile restores the private curriculum.','Boss decks, Word Book entries, Notebook items, and backups respect the same access rule.']},
 {section:'Settings and safety',icon:'âš™ï¸',title:'Accessibility, saves, and recovery',text:'Use Accessibility for text, motion, contrast, audio, explanations, and local safety snapshots.',tips:['Account export creates a portable backup containing progress, collections, settings, Notebook notes, and study records.','Safety snapshots provide local recovery points; restoring one replaces the current saved state.','Use the visible Back buttons to return to the parent menu, and avoid clearing browser storage before exporting a backup.']}
];
function ensureV6(){
 state.v6=Object.assign({tourComplete:false,onboardingGuideOffered:false,textSize:'normal',reducedMotion:false,highContrast:false,colorAssist:false,sfxVolume:70,musicVolume:35,explanations:true,feedback:[],storySeen:[],lastSnapshot:0},state.v6||{});
 if(!Array.isArray(state.v6.feedback))state.v6.feedback=[];
 if(!Array.isArray(state.v6.storySeen))state.v6.storySeen=[];
}
function esc6(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function shell(){
 if(document.getElementById('v6TourOverlay'))return;
 document.body.insertAdjacentHTML('beforeend',`
 <div id="v6TourOverlay" class="v6-overlay" aria-hidden="true"><section class="v6-dialog v6-tour-dialog"><button class="menu-back-button v6-menu-back" type="button" data-v6-back="tour">â† Menu</button><button class="v6-close" data-v6-close="tour">Ã—</button><div id="v6TourContent"></div></section></div>
 <div id="v6SettingsOverlay" class="v6-overlay" aria-hidden="true"><section class="v6-dialog"><header><button class="menu-back-button" type="button" data-v6-back="settings">â† Menu</button><div class="menu-header-copy"><span>Player comfort</span><h2>âš™ï¸ Accessibility & Settings</h2></div><button class="v6-close" data-v6-close="settings">Ã—</button></header><div id="v6SettingsContent"></div></section></div>
 <div id="v6FeedbackOverlay" class="v6-overlay" aria-hidden="true"><section class="v6-dialog"><header><button class="menu-back-button" type="button" data-v6-back="feedback">â† Menu</button><div class="menu-header-copy"><span>Help improve the mine</span><h2>ðŸ’¬ Player Feedback</h2></div><button class="v6-close" data-v6-close="feedback">Ã—</button></header><div id="v6FeedbackContent"></div></section></div>
 <div id="v6StoryToast" class="v6-story-toast" aria-live="polite"></div>`);
 document.querySelectorAll('[data-v6-close]').forEach(b=>b.onclick=()=>closeOverlay(b.dataset.v6Close));
 document.querySelectorAll('[data-v6-back]').forEach(b=>b.onclick=()=>returnToGameMenu(()=>closeOverlay(b.dataset.v6Back)));
 document.querySelectorAll('.v6-overlay').forEach(o=>o.onclick=e=>{if(e.target===o)closeOverlay(o.id.includes('Tour')?'tour':o.id.includes('Settings')?'settings':'feedback');});
}
function overlay(name){return document.getElementById(name==='tour'?'v6TourOverlay':name==='settings'?'v6SettingsOverlay':'v6FeedbackOverlay');}
function openOverlay(name){shell();const o=overlay(name);o.classList.add('open');o.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}
function closeOverlay(name){const o=overlay(name);o?.classList.remove('open');o?.setAttribute('aria-hidden','true');document.body.style.overflow='';}
let tourIndex=0;
function openTour(start=0){ensureV6();tourIndex=start;openOverlay('tour');renderTour();}
function renderTour(){const s=TOUR[tourIndex],box=document.getElementById('v6TourContent');box.innerHTML=`<div class="v6-tour-progress"><i style="width:${(tourIndex+1)/TOUR.length*100}%"></i></div><div class="v6-tour-icon">${s.icon}</div><span>${esc6(s.section)} Â· Guide ${tourIndex+1} of ${TOUR.length}</span><h2>${esc6(s.title)}</h2><p>${esc6(s.text)}</p><ul class="v6-guide-tips">${(s.tips||[]).map(tip=>`<li>${esc6(tip)}</li>`).join('')}</ul><div class="v6-tour-actions"><button id="v6TourBack" ${tourIndex===0?'disabled':''}>Back</button><button id="v6TourNext" class="primary">${tourIndex===TOUR.length-1?'Finish guide':'Next'}</button></div><button id="v6TourSkip" class="v6-link">Close guide</button>`;document.getElementById('v6TourBack').onclick=()=>{tourIndex--;renderTour();};document.getElementById('v6TourNext').onclick=()=>{if(tourIndex<TOUR.length-1){tourIndex++;renderTour();}else completeTour();};document.getElementById('v6TourSkip').onclick=completeTour;}
function completeTour(){state.v6.tourComplete=true;save();closeOverlay('tour');setMessage('Guide complete. Your Study Coach will recommend what to do next.','correct');}
function recommendation(){
 ensureV6();
 if(state.hearts<=0)return{icon:'â¤ï¸â€ðŸ©¹',title:'Hearts are recovering',text:'Use review tools or explore your collection while the recovery timer counts down.',action:'dashboard',label:'View health'};
 const due=state.v5?.srs?Object.values(state.v5.srs).filter(x=>x?.dueAt<=Date.now()).length:0;
 if(due)return{icon:'ðŸ§ ',title:`${due} review${due===1?'':'s'} ready`,text:'A short Smart Review session is the best next step for long-term memory.',action:'review',label:'Start review'};
 if(!state.active)return{icon:'â›ï¸',title:`Continue ${stages[selectedStageIndex()]?.label||'your mine'}`,text:'Use the permanent New Question button below when you are ready to continue mining.',action:'mine',label:'New question'};
 if(state.active&&!state.answered)return{icon:'ðŸŽŒ',title:'Finish your current challenge',text:'Your question is already waiting below. Read carefully, listen if available, and choose the best answer.',action:'question',label:'Return to question'};
 return{icon:'ðŸ—ºï¸',title:'Explore your next checkpoint',text:'Open the expedition map to see your current mine and upcoming guardian.',action:'map',label:'Open map'};
}
let coachHideTimer=0;
function coachShell(){let c=document.getElementById('v6CoachCard');if(!c){c=document.createElement('section');c.id='v6CoachCard';c.className='v6-coach-card';c.setAttribute('aria-live','polite');c.setAttribute('aria-hidden','true');document.querySelector('.v5-launch-card')?.after(c);}}
function coachMessage(kind){if(kind==='correct')return{icon:'âœ¨',title:'Great strike!',text:'That answer was correct. Your Japanese knowledge and mining progress both grew.',action:'',label:''};if(kind==='wrong')return{icon:'ðŸ“˜',title:'Letâ€™s learn from that',text:Number(state.hearts||0)>0?'Compare your choice with the correct answer, then keep going. Every mistake strengthens your review path.':'Your hearts are recovering. Review the explanation while your mine energy returns.',action:state.hearts>0?'':'dashboard',label:'View health'};return recommendation();}
function renderCoach(kind='question'){coachShell();const c=document.getElementById('v6CoachCard');if(!c)return;const r=coachMessage(kind),duplicate=['mine','question'].includes(r.action);c.classList.toggle('informational',duplicate||!r.action);c.innerHTML=`<div class="v6-gnome" aria-hidden="true"><i class="gnome-hat"></i><i class="gnome-face"></i><i class="gnome-nose"></i><i class="gnome-beard"></i><i class="gnome-body"></i></div><div class="v6-coach-speech"><span>KÅŒJI Â· MINE GNOME</span><h2>${r.icon} ${r.title}</h2><p>${r.text}</p></div>${!r.action?'':`<button class="primary" data-v6-coach="${r.action}">${r.label}</button>`}`;const action=c.querySelector('[data-v6-coach]');if(action)action.onclick=()=>coachAction(r.action);clearTimeout(coachHideTimer);c.classList.add('visible');c.setAttribute('aria-hidden','false');coachHideTimer=setTimeout(()=>{c.classList.remove('visible');c.setAttribute('aria-hidden','true');},7000);}
function coachAction(a){if(a==='mine'){mine();document.getElementById('challengeArea')?.scrollIntoView({behavior:'smooth'});}else if(a==='question')document.getElementById('challengeArea')?.scrollIntoView({behavior:'smooth'});else if(a==='map')window.openJapaneseMinerV5?.('map');else if(a==='review')window.openJapaneseMinerV5?.('review');else if(a==='dashboard')window.openJapaneseMinerDashboard?.('health');}
function explanation(q,chosen,correct){
 if(!state.v6.explanations||!q)return;
 let box=document.getElementById('v6AnswerExplanation');if(!box){box=document.createElement('section');box.id='v6AnswerExplanation';box.className='v6-answer-explanation';document.getElementById('message')?.after(box);}
 const answer=q.a||'',reading=q.reading||q.kana||'',meaning=q.meaning||q.en||'';
 box.innerHTML=`<span>${correct?'âœ… WHY IT WORKS':'ðŸ“˜ LEARN FROM THIS'}</span><h3>Correct answer: ${esc6(answer)}</h3>${reading&&reading!==answer?`<p><strong>Reading:</strong> ${esc6(reading)}</p>`:''}${meaning?`<p><strong>Meaning:</strong> ${esc6(meaning)}</p>`:''}<p>${correct?'You matched the prompt correctly.':'Your choice was '+esc6(chosen)+'. Compare it with the correct answer, then use Smart Review to see this item again.'}</p><div><button data-v6-explain="listen">ðŸ”Š Hear answer</button><button data-v6-explain="review">ðŸ§  Review later</button></div>`;
 box.querySelector('[data-v6-explain="listen"]').onclick=()=>speakJapanese(answer);box.querySelector('[data-v6-explain="review"]').onclick=()=>{if(state.v5?.srs&&q.id){state.v5.srs[q.id]={ease:1.8,interval:1,dueAt:Date.now()};save();setMessage('Added to Smart Review.','correct');}};
}
function applySettings(){ensureV6();document.documentElement.dataset.textSize=state.v6.textSize;document.body.dataset.reducedMotion=String(!!state.v6.reducedMotion);document.body.dataset.highContrast=String(!!state.v6.highContrast);document.body.dataset.colorAssist=String(!!state.v6.colorAssist);}
function openSettings(){ensureV6();openOverlay('settings');const box=document.getElementById('v6SettingsContent');box.innerHTML=`<div class="v6-settings-grid"><label>Text size<select id="v6TextSize"><option value="normal">Normal</option><option value="large">Large</option><option value="xlarge">Extra large</option></select></label><label class="v6-switch"><input id="v6ReducedMotion" type="checkbox"><span>Reduce animations</span></label><label class="v6-switch"><input id="v6HighContrast" type="checkbox"><span>High contrast</span></label><label class="v6-switch"><input id="v6ColorAssist" type="checkbox"><span>Color-blind indicators</span></label><label class="v6-switch"><input id="v6Explanations" type="checkbox"><span>Answer explanations</span></label><label>Sound effects <output id="v6SfxOut"></output><input id="v6Sfx" type="range" min="0" max="100"></label><label>Music <output id="v6MusicOut"></output><input id="v6Music" type="range" min="0" max="100"></label></div><section class="v6-save-recovery"><h3>ðŸ›Ÿ Save recovery</h3><p>Japanese Miner keeps rolling safety snapshots on this device.</p><div id="v6SnapshotList"></div><button id="v6SnapshotNow">Create safety snapshot</button></section>`;const bind=(id,key,type='checked')=>{const el=document.getElementById(id);el[type]=state.v6[key];el.onchange=()=>{state.v6[key]=el[type];applySettings();save();};};document.getElementById('v6TextSize').value=state.v6.textSize;document.getElementById('v6TextSize').onchange=e=>{state.v6.textSize=e.target.value;applySettings();save();};bind('v6ReducedMotion','reducedMotion');bind('v6HighContrast','highContrast');bind('v6ColorAssist','colorAssist');bind('v6Explanations','explanations');[['v6Sfx','sfxVolume','v6SfxOut'],['v6Music','musicVolume','v6MusicOut']].forEach(([id,key,out])=>{const e=document.getElementById(id),o=document.getElementById(out);e.value=state.v6[key];o.textContent=e.value+'%';e.oninput=()=>{state.v6[key]=Number(e.value);o.textContent=e.value+'%';save();};});document.getElementById('v6SnapshotNow').onclick=()=>{createSnapshot(true);renderSnapshots();};renderSnapshots();}
function snapshotKey(){return SNAPSHOT_PREFIX+(activeProfileId||'guest');}
function getSnapshots(){try{return JSON.parse(localStorage.getItem(snapshotKey())||'[]');}catch{return[];}}
function createSnapshot(force=false){ensureV6();if(!activeProfileId)return;if(!force&&Date.now()-state.v6.lastSnapshot<120000)return;const rows=getSnapshots();rows.unshift({at:Date.now(),state:JSON.parse(JSON.stringify(state))});localStorage.setItem(snapshotKey(),JSON.stringify(rows.slice(0,3)));state.v6.lastSnapshot=Date.now();}
function renderSnapshots(){const box=document.getElementById('v6SnapshotList');if(!box)return;const rows=getSnapshots();box.innerHTML=rows.map((r,i)=>`<button data-v6-restore="${i}"><strong>${new Date(r.at).toLocaleString()}</strong><small>Restore this snapshot</small></button>`).join('')||'<p>No snapshots yet.</p>';box.querySelectorAll('[data-v6-restore]').forEach(b=>b.onclick=()=>{const r=rows[Number(b.dataset.v6Restore)];if(r&&confirm('Restore this safety snapshot? Your current state will be replaced.')){state=normalizeState(r.state);repairTutorAccessState();ensureV6();save();render();closeOverlay('settings');setMessage('Safety snapshot restored.','correct');}});}
function openFeedback(){ensureV6();openOverlay('feedback');const box=document.getElementById('v6FeedbackContent');box.innerHTML=`<p>Feedback stays on this device and is included in account backups. It is never sent automatically.</p><label>Category<select id="v6FeedbackCategory"><option>Something is confusing</option><option>Learning content</option><option>Balance or rewards</option><option>Visual or mobile issue</option><option>Feature idea</option></select></label><label>Message<textarea id="v6FeedbackText" rows="5" maxlength="800" placeholder="Tell us what happened or what would improve the game..."></textarea></label><div class="v6-feedback-actions"><button id="v6SaveFeedback" class="primary">Save feedback</button><button id="v6ClearFeedback">Clear saved feedback</button></div><h3>Saved notes (${state.v6.feedback.length})</h3><div class="v6-feedback-history">${state.v6.feedback.slice().reverse().map(x=>`<article><strong>${esc6(x.category)}</strong><p>${esc6(x.text)}</p><small>${new Date(x.at).toLocaleString()}</small></article>`).join('')||'<p>No feedback saved yet.</p>'}</div>`;document.getElementById('v6SaveFeedback').onclick=()=>{const text=document.getElementById('v6FeedbackText').value.trim();if(!text)return;state.v6.feedback.push({at:Date.now(),category:document.getElementById('v6FeedbackCategory').value,text});save();openFeedback();};document.getElementById('v6ClearFeedback').onclick=()=>{if(confirm('Clear all locally saved feedback?')){state.v6.feedback=[];save();openFeedback();}};}
function addMenuItems(){const grid=document.querySelector('.menu-wheel');if(!grid||grid.querySelector('[data-v6-menu]'))return;[['guide','â”','Game Guide','Complete how-to for courses, bosses, goals, economy, and study tools','player'],['settings','âš™ï¸','Accessibility','Text, motion, contrast, audio, and recovery','player'],['feedback','ðŸ’¬','Feedback','Save play-test notes and ideas','player']].forEach(([id,icon,name,desc,cat])=>{const b=document.createElement('button');b.type='button';b.dataset.v6Menu=id;b.dataset.menuCategoryName=cat;b.innerHTML=`<span>${icon}</span><strong>${name}</strong><small>${desc}</small>`;b.onclick=()=>{closeGameMenu();id==='guide'?openTour():id==='settings'?openSettings():openFeedback();};grid.appendChild(b);});}
function storyCheck(){ensureV6();const stage=selectedStageIndex(),id='stage-'+stage;if(state.v6.storySeen.includes(id)||!activeProfileId)return;state.v6.storySeen.push(id);save();const toast=document.getElementById('v6StoryToast');if(!toast)return;const lines=['Your first lantern is lit. The Hiragana tunnels await.','Katakana markings glow on the cavern wall.','The N5 quarry opens into the wider world of Japanese.','Your journey reaches the N4 tunnel. Sentences grow richer here.','The N3 depths demand sharper reading and listening.','N2 crystals respond only to disciplined learners.','The N1 master mine stands before you.'][stage];toast.innerHTML=`<span>ðŸ“– JOURNEY UPDATE</span><strong>${stages[stage]?.name||'New mine'}</strong><p>${lines}</p>`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),5000);}
function advertiseGuideAfterOnboarding(){
 ensureV6();
 if(state.v6.onboardingGuideOffered||state.v6.tourComplete)return;
 state.v6.onboardingGuideOffered=true;
 save();
 setTimeout(()=>openTour(0),300);
}
function init(){ensureV6();shell();applySettings();coachShell();addMenuItems();storyCheck();createSnapshot();}
const oldShowQuestion=showQuestion;showQuestion=function(q){oldShowQuestion(q);renderCoach('question');};
const oldAnswer=answer;answer=function(opt,button){const q=state.active,was=state.answered,correct=!!q&&opt===q.a;if(q&&!was&&/[\u3040-\u30ff\u3400-\u9fff]/.test(stripMarkup(opt)))speakJapanese(opt);oldAnswer(opt,button);if(q&&!was){explanation(q,opt,correct);renderCoach(correct?'correct':'wrong');}createSnapshot();};
const oldRender=render;render=function(){ensureV6();oldRender();applySettings();coachShell();addMenuItems();storyCheck();};
const oldSave=save;save=function(){oldSave();if(state?.v6)createSnapshot();};
const oldLoad=loadProfile;loadProfile=function(profile){oldLoad(profile);ensureV6();applySettings();setTimeout(init,0);};
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.v6-overlay.open').forEach(o=>closeOverlay(o.id.includes('Tour')?'tour':o.id.includes('Settings')?'settings':'feedback'));});
document.addEventListener('click',e=>{if(e.target.closest?.('#beginJourneyBtn,#acceptPlacementBtn'))advertiseGuideAfterOnboarding();});
document.addEventListener('click',e=>{const toggle=e.target.closest?.('.character-option-toggle');if(!toggle)return;const section=toggle.closest('.character-option'),collapsed=section.classList.toggle('collapsed');toggle.setAttribute('aria-expanded',String(!collapsed));const key=section.dataset.characterSection;if(key)try{localStorage.setItem('jmCharacterSection:'+key,collapsed?'collapsed':'open');}catch{}});
document.addEventListener('jm-character-sections-ready',()=>document.querySelectorAll('.character-option[data-character-section]').forEach(section=>{try{if(localStorage.getItem('jmCharacterSection:'+section.dataset.characterSection)==='collapsed'){section.classList.add('collapsed');section.querySelector('.character-option-toggle')?.setAttribute('aria-expanded','false');}}catch{}}));
const characterSectionObserver=new MutationObserver(rows=>{if(rows.some(r=>[...r.addedNodes].some(n=>n.nodeType===1&&(n.matches?.('.character-option')||n.querySelector?.('.character-option')))))document.dispatchEvent(new Event('jm-character-sections-ready'));});characterSectionObserver.observe(document.body,{childList:true,subtree:true});
window.openJapaneseMinerGuide=openTour;window.openJapaneseMinerSettings=openSettings;window.openJapaneseMinerFeedback=openFeedback;
init();
})();

